language: node_js
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run prod
  - npm run test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  target-branch: gh-pages
  on:
    branch: master
